application: sydney-linux-user-group
version: 1-polleyj
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /events/add
  login: admin
  script: addevents.py
  
- url: /.*
  script: handler.py

skip_files:
- third_party/python-dateutil-1.5/
- third_party/python-datetime-tz/
- third_party/pytz/
- third_party/icalendar-2.1/
- third_party/*.tar.gz
- third_party/mkzip
- (.*/)*.git/
