application: sydney-linux-user-group-hr
version: django
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /third_party
  static_dir: static/third_party

- url: /.*
  script: main.py

skip_files:
- third_party/((?!(aeoid|python-gae-pytz)).*)/
- third_party/python-gae-pytz/(?!pytz)
- static/third_party/jquery.validation/(?!(.*.js|localization))
- third_party/aeoid/demo
- third_party/mkzip
- (.*/)*.git/
- .*/\..*
- .*/README
