application: sydney-linux-user-group
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /events/add
  login: admin
  script: addevents.py
  
- url: /.*
  script: handler.py

skip_files:
- third_party/python-dateutil-1.5/
- third_party/python-datetime-tz/
- third_party/pytz/
- third_party/*.tar.gz
- third_party/mkzip
- .git/
