application: sydney-linux-user-group-hr
version: 8
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon.ico

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /third_party
  static_dir: static/third_party

- url: /event/add
  login: admin
  script: handler-admin.py

- url: /event/[0-9]*/(edit|publish|email)
  login: admin
  script: handler-admin.py

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: handler.py

skip_files:
- third_party/aeoid/demo
- third_party/mkzip
- third_party/python-markdown/tests
- (.*/)*.git/
- .*/\..*
- .*/README
